import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json({ limit: "10mb" }));

const PORT = process.env.PORT || 5000;

const gemini = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

app.get("/", (req, res) => {
  res.send("✅ NexusOS Enterprise v2 Backend Working");
});

function cleanJSON(text) {
  return text.replace(/```json/g, "").replace(/```/g, "").trim();
}

async function askGemini(prompt) {
  const response = await gemini.models.generateContent({
    model: "gemini-2.0-flash",
    contents: prompt,
    config: {
      maxOutputTokens: 900,
    },
  });

  return response.text;
}

async function askOpenRouter(prompt) {
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "deepseek/deepseek-chat",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 900,
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error?.message || "OpenRouter failed");
  }

  return data.choices[0].message.content;
}

app.post("/api/analyze", async (req, res) => {
  try {
    const { company, content } = req.body;

    if (!content) {
      return res.status(400).json({ error: "Content is required" });
    }

    const shortContent = content.slice(0, 3000);

    const prompt = `
You are NexusOS Enterprise v2.

Analyze this using 5 AI agents:
1. Market Agent
2. Competitor Agent
3. Compliance Agent
4. Trust/Misinformation Agent
5. Strategy Agent

Company: ${company || "Unknown"}

Data:
${shortContent}

Return ONLY valid JSON:
{
  "summary": "",
  "riskScore": 0,
  "opportunityScore": 0,
  "urgencyLevel": "",
  "marketSignals": [],
  "competitorInsights": [],
  "complianceRisks": [],
  "misinformationRisks": [],
  "recommendedActions": [],
  "autoGeneratedTickets": [],
  "emailDraft": {
    "subject": "",
    "body": ""
  },
  "executiveDecision": ""
}
`;

    let aiText;
    let usedModel = "";

    try {
      aiText = await askGemini(prompt);
      usedModel = "Gemini Flash";
    } catch (err) {
      console.log("⚠️ Gemini failed/quota exhausted. Switching to OpenRouter...");
      aiText = await askOpenRouter(prompt);
      usedModel = "OpenRouter DeepSeek";
    }

    let parsed;

    try {
      parsed = JSON.parse(cleanJSON(aiText));
    } catch {
      parsed = {
        summary: aiText,
        riskScore: 50,
        opportunityScore: 50,
        urgencyLevel: "Medium",
        marketSignals: [],
        competitorInsights: [],
        complianceRisks: [],
        misinformationRisks: [],
        recommendedActions: ["Review the analysis manually."],
        autoGeneratedTickets: ["Create review task for leadership team."],
        emailDraft: {
          subject: "NexusOS Intelligence Alert",
          body: aiText,
        },
        executiveDecision: aiText,
      };
    }

    res.json({
      ...parsed,
      usedModel,
    });
  } catch (error) {
    console.error("❌ Backend Error:", error.message);

    res.status(500).json({
      error: "Analysis failed",
      details: error.message,
    });
  }
});

app.listen(PORT, () => {
  console.log(`🚀 NexusOS Enterprise v2 running on http://localhost:${PORT}`);
});