function Dashboard({ result, loading }) {
  if (loading) {
    return null;
  }

  if (!result) {
    return (
      <section className="empty-state">
        <h2>Welcome to NexusOS</h2>
        <p>
          Paste company intelligence data above and run agents to generate risk,
          opportunity, compliance, trust and strategy insights.
        </p>
      </section>
    );
  }

  return (
    <section className="dashboard-grid">
      <ScoreCard title="Risk Score" value={`${result.riskScore}/100`} icon="⚠️" />
      <ScoreCard
        title="Opportunity"
        value={`${result.opportunityScore}/100`}
        icon="📈"
      />
      <ScoreCard title="Urgency" value={result.urgencyLevel || "Medium"} icon="🚨" />
      <ScoreCard title="Model Used" value={result.usedModel || "AI"} icon="🧠" />

      <div className="panel wide">
        <h2>Executive Summary</h2>
        <p>{result.summary}</p>
      </div>

      <MiniPanel title="Market Signals" items={result.marketSignals} icon="📈" />
      <MiniPanel title="Competitor Insights" items={result.competitorInsights} icon="🏢" />
      <MiniPanel title="Compliance Risks" items={result.complianceRisks} icon="🔒" />
      <MiniPanel title="Trust Risks" items={result.misinformationRisks} icon="🛡️" />
      <MiniPanel title="Action Plan" items={result.recommendedActions} icon="✅" />
      <MiniPanel title="Tickets" items={result.autoGeneratedTickets} icon="🎫" />

      <div className="panel wide">
        <h2>Final Executive Decision</h2>
        <p>{result.executiveDecision}</p>
      </div>
    </section>
  );
}

function ScoreCard({ title, value, icon }) {
  return (
    <div className="score-card">
      <div className="score-icon">{icon}</div>
      <p>{title}</p>
      <h2>{value}</h2>
    </div>
  );
}

function MiniPanel({ title, items, icon }) {
  return (
    <div className="panel">
      <h2>
        {icon} {title}
      </h2>
      {items?.length ? (
        <ul>
          {items.slice(0, 3).map((item, index) => (
            <li key={index}>{typeof item === "string" ? item : JSON.stringify(item)}</li>
          ))}
        </ul>
      ) : (
        <p>No findings yet.</p>
      )}
    </div>
  );
}

export default Dashboard;